version: '3.8'
services:
  db:
    image: mysql:8.1
    ports:
      - '${DB_PORT}:3306'
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - lms
    restart: unless-stopped

networks:
  lms:
    driver: bridge
volumes:
  mysql:
