export enum NodeEnv {
  Development = 'development',
  Production = 'production',
}

export enum Environment {
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  DATABASE_URL = 'DATABASE_URL',
  SERVE_STATIC_ROOT_PATH = 'SERVE_STATIC_ROOT_PATH',
  ENABLE_SHUTDOWN_HOOKS = 'ENABLE_SHUTDOWN_HOOKS',
  GRAPHQL_DEBUG = 'GRAPHQL_DEBUG',
  GRAPHQL_PLAYGROUND = 'GRAPHQL_PLAYGROUND',
  GRAPHQL_INTROSPECTION = 'GRAPHQL_INTROSPECTION',
  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
}
